<?php

    function shift_cipher_menu() {
        $items = array();
        $items['shift_cipher'] = array(
            'title' => 'Shift Cipher',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => TRUE,
            'page callback' => 'drupal_get_form',
            'page arguments' => array('shift_cipher_form'),
        );
        $items['encrypted_results'] = array(
            'title' => "Encrypted Results",
            'type' => MENU_CALLBACK,
            'access callback' => TRUE,
            'page callback' => 'encrypted_results_display',
        );
        return $items;
    }

    function shift_cipher_form() {
        $form = array();
        $form['shift_value'] = array(
            '#title' => 'Shift Value',
            '#type' => 'textfield',
            '#description' => t('Enter an inteeger for the number of spaces to shift each letter'),
            '#element_validate' => array('element_validate_integer_positive'),
            '#required' => TRUE,
        );
        $form['direction'] = array(
            '#title' => 'Direction',
            '#type' => 'textfield',
            '#description' => t("Enter 'left' or 'right' depending on which way you want to shift!"),
            '#element_validate' => array('element_validate_direction'),
            '#required' => TRUE,
        );
        $form['phrase'] = array(
            '#title' => 'Phrase to Shift',
            '#type' => 'textfield',
            '#description' => t('Enter the phrase you want encrypted.'),
            '#required' => TRUE,
        );
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Encrypt!',
        );
        return $form;
    }

    function element_validate_direction($element) {
        if (strtolower($element['#value']) != 'left' && strtolower($element['#value']) != 'right' ) {
            form_error($element, t("Please enter either 'left' or 'right'!"));
        }
    }

    function shift_cipher_form_submit($form, &$form_state) {
        $shift_value = $form_state['values']['shift_value'];
        $direction = strtolower($form_state['values']['direction']);
        $phrase = strtolower($form_state['values']['phrase']);
        $words = explode(" ", $phrase);
        $shifted_words = array();

        // words is an array of each individual word from the phrase
        foreach ($words as $word) {
            $shifted_letters = array();
            // letters is an array of individual letters from the word
            $letters = str_split($word);
            foreach ($letters as $letter) {
                //turn the letter into an ascii value
                $ascii = ord($letter);
                //add or subtract the shift value
                if ($direction == 'left') {
                    $shifted_ascii = $ascii - $shift_value;
                } else if ($direction == 'right') {
                    $shifted_ascii = $ascii + $shift_value;
                }
                //convert back to a letter
                $converted_letter = chr($shifted_ascii);
                //push letter into an array of letters
                array_push($shifted_letters, $converted_letter);
            }
            //implode the array of letters to be the shifted word
            $shifted_word = implode($shifted_letters);
            //push the word into an array of words
            array_push($shifted_words, $shifted_word);
        }
        $output = implode(" ", $shifted_words);

        $_SESSION['shift_cipher_output'] = $output;
        $form_state['redirect'] = 'encrypted_results';
    }

    function encrypted_results_display() {
        $results = $_SESSION['shift_cipher_output'];

        return "<p> $results </p>";
    }


// 97 = a
// 122 = z
