<?php

    function shift_cipher_menu() {
        $items = array();
        $items['shift_cipher'] = array(
            'title' => 'Shift Cipher',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => TRUE,
            'page callback' => 'drupal_get_form',
            'page arguments' => array('shift_cipher_form'),
        );
        $items['encrypted_results'] = array(
            'title' => "Encrypted Results",
            'type' => MENU_CALLBACK,
            'access callback' => TRUE,
            'page callback' => 'encrypted_results_display',
        );
        return $items;
    }

    function shift_cipher_form() {
        $form = array();
        $form['shift_value'] = array(
            '#title' => 'Shift Value',
            '#type' => 'textfield',
            '#description' => t('Enter an inteeger for the number of spaces to shift each letter'),
            '#element_validate' => array('element_validate_integer_positive'),
            '#required' => TRUE,
        );
        $form['direction'] = array(
            '#title' => 'Direction',
            '#type' => 'textfield',
            '#description' => t("Enter 'left' or 'right' depending on which way you want to shift!"),
            '#required' => TRUE,
        );
        $form['phrase'] = array(
            '#title' => 'Phrase to Shift',
            '#type' => 'textfield',
            '#description' => t('Enter the phrase you want encrypted.'),
            '#required' => TRUE,
        );
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => 'Encrypt!',
        );
        return $form;
    }

    function shift_cipher_form_submit($form, &$form_state) {
        $shift_value = $form_state['values']['shift_value'];
        $direction = $form_state['values']['direction'];
        $phrase = $form_state['values']['phrase'];

        $_SESSION['shift_cipher_output'] = $output;
        $form_state['redirect'] = 'encrypted_results';
    }

    function encrypted_results_display() {
        $results = $_SESSION['shift_cipher_output'];

        return "<p> $results </p>";
    }
